python3 halftones.py images/baboon.png all gray;
python3 halftones.py images/baboon.png all gray --zigzag;
python3 halftones.py images/baboon.png all bgr;
python3 halftones.py images/baboon.png all bgr --zigzag;
python3 halftones.py images/baboon.png all hsv;
python3 halftones.py images/baboon.png all hsv --zigzag;
python3 halftones.py images/monalisa.png all gray;
python3 halftones.py images/monalisa.png all gray --zigzag;
python3 halftones.py images/monalisa.png all bgr;
python3 halftones.py images/monalisa.png all bgr --zigzag;
python3 halftones.py images/monalisa.png all hsv;
python3 halftones.py images/monalisa.png all hsv --zigzag;
python3 halftones.py images/peppers.png all gray;
python3 halftones.py images/peppers.png all gray --zigzag;
python3 halftones.py images/peppers.png all bgr;
python3 halftones.py images/peppers.png all bgr --zigzag;
python3 halftones.py images/peppers.png all hsv;
python3 halftones.py images/peppers.png all hsv --zigzag;
python3 halftones.py images/watch.png all gray;
python3 halftones.py images/watch.png all gray --zigzag;
python3 halftones.py images/watch.png all bgr;
python3 halftones.py images/watch.png all bgr --zigzag;
python3 halftones.py images/watch.png all hsv;
python3 halftones.py images/watch.png all hsv --zigzag;