python3 summarize.py ./videos/indi009.mpg pixels
python3 summarize.py ./videos/indi009.mpg blocks
python3 summarize.py ./videos/indi009.mpg histograms
python3 summarize.py ./videos/indi009.mpg edges
python3 summarize.py ./videos/lisa.mpg pixels
python3 summarize.py ./videos/lisa.mpg blocks
python3 summarize.py ./videos/lisa.mpg histograms
python3 summarize.py ./videos/lisa.mpg edges
python3 summarize.py ./videos/news.mpg pixels
python3 summarize.py ./videos/news.mpg blocks
python3 summarize.py ./videos/news.mpg histograms
python3 summarize.py ./videos/news.mpg edges
