python3 summarize.py ./videos/color/indi009.mpg pixels
python3 summarize.py ./videos/color/indi009.mpg blocks
python3 summarize.py ./videos/color/indi009.mpg histograms
python3 summarize.py ./videos/color/indi009.mpg edges
python3 summarize.py ./videos/color/lisa.mpg pixels
python3 summarize.py ./videos/color/lisa.mpg blocks
python3 summarize.py ./videos/color/lisa.mpg histograms
python3 summarize.py ./videos/color/lisa.mpg edges
python3 summarize.py ./videos/color/news.mpg pixels
python3 summarize.py ./videos/color/news.mpg blocks
python3 summarize.py ./videos/color/news.mpg histograms
python3 summarize.py ./videos/color/news.mpg edges
python3 summarize.py ./videos/color/selena.mp4 pixels
python3 summarize.py ./videos/color/selena.mp4 blocks
python3 summarize.py ./videos/color/selena.mp4 histograms
python3 summarize.py ./videos/color/selena.mp4 edges
python3 summarize.py ./videos/color/toy.mp4 pixels
python3 summarize.py ./videos/color/toy.mp4 blocks
python3 summarize.py ./videos/color/toy.mp4 histograms
python3 summarize.py ./videos/color/toy.mp4 edges
python3 summarize.py ./videos/color/UGS09.mpg pixels
python3 summarize.py ./videos/color/UGS09.mpg blocks
python3 summarize.py ./videos/color/UGS09.mpg histograms
python3 summarize.py ./videos/color/UGS09.mpg edges
python3 summarize.py ./videos/color/umn.mp4 pixels
python3 summarize.py ./videos/color/umn.mp4 blocks
python3 summarize.py ./videos/color/umn.mp4 histograms
python3 summarize.py ./videos/color/umn.mp4 edges
python3 summarize.py ./videos/color/xylophone.mp4 pixels
python3 summarize.py ./videos/color/xylophone.mp4 blocks
python3 summarize.py ./videos/color/xylophone.mp4 histograms
python3 summarize.py ./videos/color/xylophone.mp4 edges
python3 summarize.py ./videos/color/08024.mpg pixels
python3 summarize.py ./videos/color/08024.mpg blocks
python3 summarize.py ./videos/color/08024.mpg histograms
python3 summarize.py ./videos/color/08024.mpg edges
python3 summarize.py ./videos/color/08386.mpg pixels
python3 summarize.py ./videos/color/08386.mpg blocks
python3 summarize.py ./videos/color/08386.mpg histograms
python3 summarize.py ./videos/color/08386.mpg edges
python3 summarize.py ./videos/color/08401.mpg pixels
python3 summarize.py ./videos/color/08401.mpg blocks
python3 summarize.py ./videos/color/08401.mpg histograms
python3 summarize.py ./videos/color/08401.mpg edges
python3 summarize.py ./videos/color/36553.mpg pixels
python3 summarize.py ./videos/color/36553.mpg blocks
python3 summarize.py ./videos/color/36553.mpg histograms
python3 summarize.py ./videos/color/36553.mpg edges
